In [1]:
import pandas as pd

Task: 

Hai un DataFrame con le colonne Gene, Espressione_Controllo e Espressione_Trattato. 

Devi creare una nuova colonna chiamata Status_Regolazione.

Usa apply impostando axis='columns' (o axis=1) per passare l'intera riga a una funzione personalizzata. La funzione dovrà valutare le due colonne simultaneamente:

- Se Espressione_Trattato è almeno il doppio di Espressione_Controllo, restituisci la stringa "Up-regolato".

- Se è la metà (o meno), restituisci "Down-regolato".

- In tutti gli altri casi, restituisci "Stabile".

In [3]:

dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}
df= pd.DataFrame(dati)

display(df)

    Gene  Espressione_Controllo  Espressione_Trattato
0  BRCA1                   10.5                  11.0
1   TP53                   45.2                  15.1
2    MYC                    5.0                  15.0
3   EGFR                  100.0                 105.0
4   KRAS                   20.0                   8.5

In [16]:
dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}

df= pd.DataFrame(dati)



def diff(riga):
    
    
    out=""

    if riga["Espressione_Trattato"]>=(riga["Espressione_Controllo"]*2):
        out="Up-regolato"
    
    elif riga["Espressione_Trattato"]<=(riga["Espressione_Controllo"]/2):
        out="Down-regolato"
    else:
        out="Stabile"
    return(out)


df["Status_Regolazione"]=df.apply(diff, axis="columns")


display(df)

    Gene  Espressione_Controllo  Espressione_Trattato Status_Regolazione
0  BRCA1                   10.5                  11.0            Stabile
1   TP53                   45.2                  15.1      Down-regolato
2    MYC                    5.0                  15.0        Up-regolato
3   EGFR                  100.0                 105.0            Stabile
4   KRAS                   20.0                   8.5      Down-regolato

In [17]:
dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}

df= pd.DataFrame(dati)



def diff(riga):

    if riga["Espressione_Trattato"]>=(riga["Espressione_Controllo"]*2):
        return "Up-regolato"
    
    elif riga["Espressione_Trattato"]<=(riga["Espressione_Controllo"]/2):
        return "Down-regolato"
    else:
        return "Stabile"
    


df["Status_Regolazione"]=df.apply(diff, axis="columns")


display(df)

    Gene  Espressione_Controllo  Espressione_Trattato Status_Regolazione
0  BRCA1                   10.5                  11.0            Stabile
1   TP53                   45.2                  15.1      Down-regolato
2    MYC                    5.0                  15.0        Up-regolato
3   EGFR                  100.0                 105.0            Stabile
4   KRAS                   20.0                   8.5      Down-regolato

In [ ]:
dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}

df= pd.DataFrame(dati)


def diff(riga):

    tratt=riga["Espressione_Trattato"]
    contr=riga["Espressione_Controllo"]


    if tratt>=(contr*2):

        return "Up-regolato"


    elif tratt<=(contr/2):

        return "Down-regolato"

    else:

        return "Stabile"






df["Status_Regolazione"]=df[["Espressione_Controllo","Espressione_Trattato"]].apply(diff, axis="columns")





display(df)

    Gene  Espressione_Controllo  Espressione_Trattato Status_Regolazione
0  BRCA1                   10.5                  11.0            Stabile
1   TP53                   45.2                  15.1      Down-regolato
2    MYC                    5.0                  15.0        Up-regolato
3   EGFR                  100.0                 105.0            Stabile
4   KRAS                   20.0                   8.5      Down-regolato

In [13]:
dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}

df= pd.DataFrame(dati)


def diff(tratt,contr):
    out=[]

    for riga in range(len(tratt)):

        if tratt.iloc[riga]>=(contr.iloc[riga]*2):

            out.append("Up-regolato")


        elif tratt.iloc[riga]<=(contr.iloc[riga]/2):

             out.append("Down-regolato")

        else:

             out.append("Stabile")
    
    return(out)





df["Status_Regolazione"]=diff(df["Espressione_Controllo"], df["Espressione_Trattato"])





display(df)

    Gene  Espressione_Controllo  Espressione_Trattato Status_Regolazione
0  BRCA1                   10.5                  11.0            Stabile
1   TP53                   45.2                  15.1        Up-regolato
2    MYC                    5.0                  15.0      Down-regolato
3   EGFR                  100.0                 105.0            Stabile
4   KRAS                   20.0                   8.5        Up-regolato

In [14]:
dati = {
    'Gene': ['BRCA1', 'TP53', 'MYC', 'EGFR', 'KRAS'],
    'Espressione_Controllo':[10.5, 45.2, 5.0, 100.0, 20.0],
    'Espressione_Trattato':[11.0, 15.1, 15.0, 105.0, 8.5]
}

df= pd.DataFrame(dati)


def diff(tratt,contr):
    out=""

    for riga in range(len(tratt)):

        if tratt.iloc[riga]>=(contr.iloc[riga]*2):

            out="Up-regolato"


        elif tratt.iloc[riga]<=(contr.iloc[riga]/2):

             out="Down-regolato"

        else:

             out="Stabile"
    
    return(out)





df["Status_Regolazione"]=diff(df["Espressione_Controllo"], df["Espressione_Trattato"])





display(df)

    Gene  Espressione_Controllo  Espressione_Trattato Status_Regolazione
0  BRCA1                   10.5                  11.0        Up-regolato
1   TP53                   45.2                  15.1        Up-regolato
2    MYC                    5.0                  15.0        Up-regolato
3   EGFR                  100.0                 105.0        Up-regolato
4   KRAS                   20.0                   8.5        Up-regolato