In [ ]:
import pandas as pd
print("Funziona!")

1. Creazione e Lettura Dati (DataFrame, read_csv)

Task: Crea manualmente un DataFrame contenente 3 geni (BRCA1, TP53, EGFR), i loro livelli di espressione (es. 15.4, 2.1, 8.9) e il cromosoma di appartenenza. Salvalo come CSV e poi rileggilo usando index_col per impostare il nome del gene come indice.

In [29]:
gen_expr = pd.DataFrame([{"BRCA1":15.4, "TP53":2.1, "EGFR":8.9},{"BRCA1":67.4, "TP53":4, "EGFR":34.7}],index=["expression","expression"]) 

display(gen_expr)

            BRCA1  TP53  EGFR
expression   15.4   2.1   8.9
expression   67.4   4.0  34.7

In [34]:
gen_expr = pd.DataFrame([{"expr_1":89.7,"expr_2":44,"expr_3":45.1}],index=["BRCA1", "TP53", "EGFR"]) 

display(gen_expr)

       expr_1  expr_2  expr_3
BRCA1    89.7      44    45.1
TP53     89.7      44    45.1
EGFR     89.7      44    45.1

In [36]:
gen_expr = {

"BRCA1":[14.6,78], 
"TP53":[45.8,34], 
"EGFR":[82.2,47.8]
   
}

display(pd.DataFrame(gen_expr))

   BRCA1  TP53  EGFR
0   14.6  45.8  82.2
1   78.0  34.0  47.8

In [ ]:
gen_expr = pd.DataFrame([{"BRCA1":15.4, "TP53":2.1, "EGFR":8.9},{"BRCA1":12, "TP53":8, "EGFR":22}],index=["expression","chromosome"]) 

gen_expr.to_csv("espressione_genica.csv")

pd.read_csv("espressione_genica.csv",index_col=0)

#display(gen_expr)

            BRCA1  TP53  EGFR
expression   15.4   2.1   8.9
cromosome    12.0   8.0  22.0

In [51]:
data = {
    "BRCA1": [15.4, 17],
    "TP53": [2.1, 17],
    "EGFR": [8.9, 7]
}


gen_expr = pd.DataFrame(data, index=["expression", "chromosome"])


gen_expr.to_csv("espressione_genica_new.csv")
pd.read_csv("espressione_genica_new.csv", index_col=0)

            BRCA1  TP53  EGFR
expression   15.4   2.1   8.9
chromosome   17.0  17.0   7.0

In [4]:
import pandas as pd

# --- PASSO 1: Creazione Manuale del DataFrame ---
# Definiamo i dati manualmente in un dizionario per chiarezza
dati = {
    'Gene': ['BRCA1', 'TP53', 'EGFR'],
    'Livello_Espressione': [15.4, 2.1, 8.9],
    'Cromosoma': ['chr17', 'chr17', 'chr7'] # Dati realistici per questi geni
}

# Creiamo il DataFrame
df = pd.DataFrame(dati)



# --- PASSO 2: Salvataggio come CSV ---
# Salviamo il file. Usiamo index=False per non salvare l'indice di pandas (che è 0,1,2...)
# nel file CSV, così quando lo rileggiamo possiamo decidere quale colonna usare come indice.
nome_file = 'dati_geni.csv'
df.to_csv(nome_file, index=False)



# --- PASSO 3: Lettura del CSV con index_col ---
# Rileggiamo il file specificando che la colonna 'Gene' deve diventare l'indice.
pd.read_csv(nome_file, index_col=0)

       Livello_Espressione Cromosoma
Gene
BRCA1                 15.4     chr17
TP53                   2.1     chr17
EGFR                   8.9      chr7