In [94]:
import pandas as pd

2. Indicizzazione e Selezione (loc, iloc, Condizioni)

Task: Carica un dataset di varianti genomiche (VCF simulato). Usa iloc per estrarre le prime 10 varianti. Usa loc e la selezione condizionale per trovare tutte le mutazioni nel gene "KRAS" che hanno un punteggio di patogenicità (pathogenicity_score) superiore a 0.8 e (&) una frequenza allelica (AF) minore di 0.01.

In [95]:
dati_finti = {
    'ID': ['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12'],
    'gene': ['TP53', 'KRAS', 'BRCA1', 'KRAS', 'EGFR', 'KRAS', 'KRAS', 'TP53', 'KRAS', 'ALK', 'KRAS', 'KRAS'],
    'pathogenicity_score': [0.9, 0.85, 0.6, 0.95, 0.4, 0.82, 0.5, 0.99, 0.9, 0.88, 0.81, 0.79],
    'AF': [0.05, 0.005, 0.1, 0.0001, 0.2, 0.009, 0.5, 0.001, 0.02, 0.0005, 0.008, 0.001]
}

df = pd.DataFrame(dati_finti)

display(df)

       ID   gene  pathogenicity_score      AF
0    var1   TP53                 0.90  0.0500
1    var2   KRAS                 0.85  0.0050
2    var3  BRCA1                 0.60  0.1000
3    var4   KRAS                 0.95  0.0001
4    var5   EGFR                 0.40  0.2000
5    var6   KRAS                 0.82  0.0090
6    var7   KRAS                 0.50  0.5000
7    var8   TP53                 0.99  0.0010
8    var9   KRAS                 0.90  0.0200
9   var10    ALK                 0.88  0.0005
10  var11   KRAS                 0.81  0.0080
11  var12   KRAS                 0.79  0.0010

In [ ]:
dati_finti = {
    'ID': ['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12'],
    'gene': ['TP53', 'KRAS', 'BRCA1', 'KRAS', 'EGFR', 'KRAS', 'KRAS', 'TP53', 'KRAS', 'ALK', 'KRAS', 'KRAS'],
    'pathogenicity_score': [0.9, 0.85, 0.6, 0.95, 0.4, 0.82, 0.5, 0.99, 0.9, 0.88, 0.81, 0.79],
    'AF': [0.05, 0.005, 0.1, 0.0001, 0.2, 0.009, 0.5, 0.001, 0.02, 0.0005, 0.008, 0.001]
}

df = pd.DataFrame(dati_finti)

first_10=df.iloc[:10]

display(first_10)

kras_mut=df.loc[(df["gene"]=="KRAS") & (df["pathogenicity_score"]>0.8) & (df["AF"]<0.01)]

display(kras_mut)

      ID   gene  pathogenicity_score      AF
0   var1   TP53                 0.90  0.0500
1   var2   KRAS                 0.85  0.0050
2   var3  BRCA1                 0.60  0.1000
3   var4   KRAS                 0.95  0.0001
4   var5   EGFR                 0.40  0.2000
5   var6   KRAS                 0.82  0.0090
6   var7   KRAS                 0.50  0.5000
7   var8   TP53                 0.99  0.0010
8   var9   KRAS                 0.90  0.0200
9  var10    ALK                 0.88  0.0005

       ID  gene  pathogenicity_score      AF
1    var2  KRAS                 0.85  0.0050
3    var4  KRAS                 0.95  0.0001
5    var6  KRAS                 0.82  0.0090
10  var11  KRAS                 0.81  0.0080

In [97]:
dati_finti = {
    'ID': ['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12'],
    'gene': ['TP53', 'KRAS', 'BRCA1', 'KRAS', 'EGFR', 'KRAS', 'KRAS', 'TP53', 'KRAS', 'ALK', 'KRAS', 'KRAS'],
    'pathogenicity_score': [0.9, 0.85, 0.6, 0.95, 0.4, 0.82, 0.5, 0.99, 0.9, 0.88, 0.81, 0.79],
    'AF': [0.05, 0.005, 0.1, 0.0001, 0.2, 0.009, 0.5, 0.001, 0.02, 0.0005, 0.008, 0.001]
}

df = pd.DataFrame(dati_finti)

kras=df.gene.map(lambda p: p=="TP53").sum()
#print(kras)
display(float(kras))

#display(df)
#kras.to_csv("es_kras.csv")

#pd.read_csv("es_kras.csv")

2.0

In [98]:
dati_finti = {
    'ID': ['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12'],
    'gene': ['TP53', 'KRAS', 'BRCA1', 'KRAS', 'EGFR', 'KRAS', 'KRAS', 'TP53', 'KRAS', 'ALK', 'KRAS', 'KRAS'],
    'pathogenicity_score': [0.9, 0.85, 0.6, 0.95, 0.4, 0.82, 0.5, 0.99, 0.9, 0.88, 0.81, 0.79],
    'AF': [0.05, 0.005, 0.1, 0.0001, 0.2, 0.009, 0.5, 0.001, 0.02, 0.0005, 0.008, 0.001]
}

df = pd.DataFrame(dati_finti)
conta=df.gene.value_counts()

display(conta)
display(int(df.gene.value_counts().sum()))

gene
KRAS     7
TP53     2
BRCA1    1
EGFR     1
ALK      1
Name: count, dtype: int64

12

In [99]:
dati_finti = {
    'ID': ['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12'],
    'gene': ['TP53', 'KRAS', 'BRCA1', 'KRAS', 'EGFR', 'KRAS', 'KRAS', 'TP53', 'KRAS', 'ALK', 'KRAS', 'KRAS'],
    'pathogenicity_score': [0.9, 0.85, 0.6, 0.95, 0.4, 0.82, 0.5, 0.99, 0.9, 0.88, 0.81, 0.79],
    'AF': [0.05, 0.005, 0.1, 0.0001, 0.2, 0.009, 0.5, 0.001, 0.02, 0.0005, 0.008, 0.001]
}

df = pd.DataFrame(dati_finti)


media= df.pathogenicity_score.mean()
print(df.pathogenicity_score.map(lambda p: p))
print(f"la media è:{round(media,2)}")

0     0.90
1     0.85
2     0.60
3     0.95
4     0.40
5     0.82
6     0.50
7     0.99
8     0.90
9     0.88
10    0.81
11    0.79
Name: pathogenicity_score, dtype: float64
la media è:0.78