In [6]:
import pandas as pd

4. Raggruppamento e Ordinamento (groupby, sort_values)

Task: Hai un dataset RNA-seq di pazienti sani e malati. Usa groupby sulla colonna Condition (Healthy/Tumor) per calcolare la media (mean()) dell'espressione del gene "MYC". Usa sort_values in ordine decrescente (ascending=False) per trovare i 5 pazienti con l'espressione più alta in assoluto.

In [3]:
data = {
    'Patient_ID': ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08'],
    'Condition': ['Healthy', 'Healthy', 'Healthy', 'Tumor', 'Tumor', 'Healthy', 'Healthy', 'Tumor'],
    'MYC': [1.2, 15.4, 0.9, 12.1, 1.5, 18.2, 0.8, 14.7]
}

df = pd.DataFrame(data)

display(df)

  Patient_ID Condition   MYC
0        P01   Healthy   1.2
1        P02   Healthy  15.4
2        P03   Healthy   0.9
3        P04     Tumor  12.1
4        P05     Tumor   1.5
5        P06   Healthy  18.2
6        P07   Healthy   0.8
7        P08     Tumor  14.7

In [25]:
data = {
    'Patient_ID': ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08'],
    'Condition': ['Healthy', 'Healthy', 'Healthy', 'Tumor', 'Tumor', 'Healthy', 'Healthy', 'Tumor'],
    'MYC': [1.2, 15.4, 0.9, 12.1, 1.5, 18.2, 0.8, 14.7]
}

df = pd.DataFrame(data)

media_MYC=df.groupby("Condition").MYC.mean()
top_pat=df.groupby("Patient_ID").MYC.apply(lambda p: max(p)).sort_values(ascending=False).head(5)

display(media_MYC,top_pat)

Condition
Healthy    7.300000
Tumor      9.433333
Name: MYC, dtype: float64

Patient_ID
P06    18.2
P02    15.4
P08    14.7
P04    12.1
P05     1.5
Name: MYC, dtype: float64

In [36]:
data = {
    'Patient_ID': ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08'],
    'Condition': ['Healthy', 'Healthy', 'Healthy', 'Tumor', 'Tumor', 'Healthy', 'Healthy', 'Tumor'],
    'MYC': [1.2, 15.4, 0.9, 12.1, 1.5, 18.2, 0.8, 14.7]
}

df = pd.DataFrame(data)

media_MYC=df.groupby("Condition").MYC.mean()
top_pat=df.groupby("Patient_ID").MYC.max().sort_values(ascending=False).head(5)

display(media_MYC,top_pat)

Condition
Healthy    7.300000
Tumor      9.433333
Name: MYC, dtype: float64

Patient_ID
P06    18.2
P02    15.4
P08    14.7
P04    12.1
P05     1.5
Name: MYC, dtype: float64

In [97]:
data = {
    'Patient_ID': ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08'],
    'Condition': ['Healthy', 'Healthy', 'Healthy', 'Tumor', 'Tumor', 'Healthy', 'Healthy', 'Tumor'],
    'MYC': [1.2, 15.4, 0.9, 12.1, 1.5, 18.2, 0.8, 14.7]
}

df = pd.DataFrame(data)

media_MYC=df.groupby("Condition").MYC.mean()
top_pat=df.groupby("Patient_ID").MYC.max().sort_values(ascending=False).head(5)
media_MYC.to_csv("media_gene.csv")
top_pat.to_csv("pazienti.csv")


display(pd.read_csv("media_gene.csv"))
display(pd.read_csv("pazienti.csv"))

  Condition       MYC
0   Healthy  7.300000
1     Tumor  9.433333

  Patient_ID   MYC
0        P06  18.2
1        P02  15.4
2        P08  14.7
3        P04  12.1
4        P05   1.5