In [1]:
import pandas as pd

6. Rinominare e Combinare (rename, concat, join)

Task: Hai due file CSV: uno con i metadati dei pazienti (Patient_ID, Age, Stage) e uno con l'espressione genica (Patient_ID, TP53_expr, BRCA1_expr). Uniscili usando un join (o merge) sulla colonna Patient_ID. Usa rename per cambiare Stage in Tumor_Stage.

In [ ]:

df_clinico = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P004'],
    'Age': [45, 62, 38, 55],
    'Stage': ['I', 'III', 'II', 'IV']
})

df_genica = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P005'], 
    'TP53_expr': [12.5, 8.2, 15.1, 9.4],
    'BRCA1_expr': [5.1, 4.8, 7.2, 6.3]
})

display("DataFrame Clinico:\n", df_clinico)
display("\nDataFrame Espressione Genica:\n", df_genica)

'DataFrame Clinico:\n'

  Patient_ID  Age Stage
0       P001   45     I
1       P002   62   III
2       P003   38    II
3       P004   55    IV

'\nDataFrame Espressione Genica:\n'

  Patient_ID  TP53_expr  BRCA1_expr
0       P001       12.5         5.1
1       P002        8.2         4.8
2       P003       15.1         7.2
3       P005        9.4         6.3

In [52]:

clinico = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P004'],
    'Age': [45, 62, 38, 55],
    'Stage': ['I', 'III', 'II', 'IV']
})

genica = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P005'], 
    'TP53_expr': [12.5, 8.2, 15.1, 9.4],
    'BRCA1_expr': [5.1, 4.8, 7.2, 6.3]
})

clinico=clinico.set_index('Patient_ID')
genica=genica.set_index('Patient_ID')

pd.DataFrame(clinico.join(genica,lsuffix="_clin", rsuffix="_gen", how="outer")).rename(columns={"Stage":"Tumor_Stage"})

             Age Tumor_Stage  TP53_expr  BRCA1_expr
Patient_ID
P001        45.0           I       12.5         5.1
P002        62.0         III        8.2         4.8
P003        38.0          II       15.1         7.2
P004        55.0          IV        NaN         NaN
P005         NaN         NaN        9.4         6.3

In [62]:

clinico = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P004'],
    'Age': [45, 62, 38, 55],
    'Stage': ['I', 'III', 'II', 'IV']
})

genica = pd.DataFrame({
    'Patient_ID': ['P001', 'P002', 'P003', 'P005'], 
    'TP53_expr': [12.5, 8.2, 15.1, 9.4],
    'BRCA1_expr': [5.1, 4.8, 7.2, 6.3]
})


pd.merge(clinico,genica, how="outer").rename(columns={"Stage":"Tumor_Stage"})

  Patient_ID   Age Tumor_Stage  TP53_expr  BRCA1_expr
0       P001  45.0           I       12.5         5.1
1       P002  62.0         III        8.2         4.8
2       P003  38.0          II       15.1         7.2
3       P004  55.0          IV        NaN         NaN
4       P005   NaN         NaN        9.4         6.3