In [46]:
import pandas as pd

3. Funzioni di Sintesi e Mappe (describe, value_counts, apply, map)

Task: Hai una colonna con sequenze di DNA. Usa apply con una funzione lambda o personalizzata per calcolare la lunghezza di ogni sequenza e creare una nuova colonna Seq_Length. Usa value_counts() su una colonna Consequence (es. missense, frameshift, silent) per vedere quante mutazioni ci sono per tipo.

In [ ]:
data = {
    'DNA_Sequence': ['ATGCGT', 'ATGC', 'GGGTTAACCA', 'ATGCGTACGT', 'TAGA', 'ATGCGT'],
    'Consequence': ['missense', 'silent', 'missense', 'frameshift', 'silent', 'missense']
}

df = pd.DataFrame(data)

display(df)

  DNA_Sequence Consequence
0       ATGCGT    missense
1         ATGC      silent
2   GGGTTAACCA    missense
3   ATGCGTACGT  frameshift
4         TAGA      silent
5       ATGCGT    missense

In [ ]:
data = {
    'DNA_Sequence': ['ATGCGT', 'ATGC', 'GGGTTAACCA', 'ATGCGTACGT', 'TAGA', 'ATGCGT'],
    'Consequence': ['missense', 'silent', 'missense', 'frameshift', 'silent', 'missense']
}

df = pd.DataFrame(data)

# display(df)

def lung(string):
    count=0
    for nuc in string:
        count+=1
    return count

df["Seq_Length"]= df["DNA_Sequence"].apply(lung)


mut= df.Consequence.value_counts()

display(df[["Seq_Length","DNA_Sequence"]])
display(mut)

   Seq_Length DNA_Sequence
0           6       ATGCGT
1           4         ATGC
2          10   GGGTTAACCA
3          10   ATGCGTACGT
4           4         TAGA
5           6       ATGCGT

Consequence
missense      3
silent        2
frameshift    1
Name: count, dtype: int64

In [ ]:


df = pd.DataFrame([{"DNA_Sequence":"ATGCGT","Consequence":"missense"},{"DNA_Sequence":"ATGC","Consequence":"silent"},{"DNA_Sequence":"GGGTTAACCA","Consequence":"missense"},{"DNA_Sequence":"ATGCGTACGT","Consequence":"frameshift"},{"DNA_Sequence":"TAGA","Consequence":"silent"},{"DNA_Sequence":"ATGCGT","Consequence":"missense"}])

# display(df)

df["lunghezza"]=df.DNA_Sequence.apply(lambda p: len(p))

conta=df.Consequence.value_counts()
display(df[["lunghezza","DNA_Sequence"]])

display(conta)

   lunghezza DNA_Sequence
0          6       ATGCGT
1          4         ATGC
2         10   GGGTTAACCA
3         10   ATGCGTACGT
4          4         TAGA
5          6       ATGCGT

DNA_Sequence
ATGCGT        2
ATGC          1
GGGTTAACCA    1
ATGCGTACGT    1
TAGA          1
Name: count, dtype: int64

In [87]:

dati={

"DNA_Sequence":["ATGCGT","ATGC","GGGTTAACCA","ATGCGTACGT","TAGA","ATGCGT"],
"Consequence":["missense","silent","missense","frameshift","silent","missense"]

    
}

df = pd.DataFrame(dati)

# display(df)

def lung(seq):
    return (len(seq))
    
df["lunghezza"]=df.DNA_Sequence.apply(lung)

conta=df.Consequence.value_counts()

display(df[["lunghezza","DNA_Sequence"]])
display(conta)

   lunghezza DNA_Sequence
0          6       ATGCGT
1          4         ATGC
2         10   GGGTTAACCA
3         10   ATGCGTACGT
4          4         TAGA
5          6       ATGCGT

Consequence
missense      3
silent        2
frameshift    1
Name: count, dtype: int64

In [99]:

dati={

"DNA_Sequence":["ATGCGT","ATGC","GGGTTAACCA","ATGCGTACGT","TAGA","ATGCGT"],
"Consequence":["missense","silent","missense","frameshift","silent","missense"]

    
}

df = pd.DataFrame(dati)

# display(df)

def lung(seq):
    c=0
    while c<len(seq):
        c+=1
    return c

df["lunghezza"]=df.DNA_Sequence.map(lung)

conta=df.Consequence.value_counts()

display(df[["lunghezza","DNA_Sequence"]])
display(conta)

   lunghezza DNA_Sequence
0          6       ATGCGT
1          4         ATGC
2         10   GGGTTAACCA
3         10   ATGCGTACGT
4          4         TAGA
5          6       ATGCGT

Consequence
missense      3
silent        2
frameshift    1
Name: count, dtype: int64

In [92]:
dati={

"DNA_Sequence":["ATGCGT","ATGC","GGGTTAACCA","ATGCGTACGT","TAGA","ATGCGT"],
"Consequence":["missense","silent","missense","frameshift","silent","missense"]

    
}

df = pd.DataFrame(dati)

df["lunghezza"]=df.DNA_Sequence.apply(lambda p: len(p))

conta=df.Consequence.value_counts()

display(df[["lunghezza","DNA_Sequence"]])
display(conta)

   lunghezza DNA_Sequence
0          6       ATGCGT
1          4         ATGC
2         10   GGGTTAACCA
3         10   ATGCGTACGT
4          4         TAGA
5          6       ATGCGT

Consequence
missense      3
silent        2
frameshift    1
Name: count, dtype: int64