In [1]:
import pandas as pd

5. Tipi di dati e Dati Mancanti (dtypes, fillna, replace)

Task: Carica dati clinici dei pazienti. Controlla i dtypes. La colonna Age ha dei valori vuoti (NaN): riempili (fillna) con l'età mediana del gruppo. La colonna Sex contiene valori come "M", "F", ma anche "Unknown": usa replace() per trasformare "Unknown" in NaN (usando np.nan della libreria numpy).

In [24]:
data = {
    'Age': [25, 30, None, 45, None, 50],
    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']
}

df = pd.DataFrame(data)

display(df)

    Age      Sex
0  25.0        M
1  30.0        F
2   NaN  Unknown
3  45.0        M
4   NaN        F
5  50.0  Unknown

In [55]:
data = {

    'Age': [25, 30, None, 45, None, 50],

    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']

}



df = pd.DataFrame(data)



display(df.dtypes)



df.fillna(df.Age.median()).replace("Unknown", None).to_csv("sostituzioni.csv", index=False)

display(pd.read_csv("sostituzioni.csv"))

Age    float64
Sex        str
dtype: object

    Age  Sex
0  25.0    M
1  30.0    F
2  37.5  NaN
3  45.0    M
4  37.5    F
5  50.0  NaN

In [42]:
import pandas as pd
import numpy as np

# 1. Caricamento dati
data = {
    'Age': [25, 30, None, 45, None, 50],
    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']
}

df = pd.DataFrame(data)

# 2. Controllo dei dtypes
print("Dtypes iniziali:")
print(df.dtypes)
print("-" * 30)

# 3. Trasformazione "Unknown" in NaN (Usando np.nan come richiesto)
# Facciamo questo per PRIMO, così il dataset è "pulito" e uniforme
df['Sex'] = df['Sex'].replace("Unknown", np.nan)

# 4. Riempimento dei vuoti nella colonna Age con la mediana
# Calcoliamo la mediana e la applichiamo SOLO alla colonna Age
mediana_age = df['Age'].median()
df['Age'] = df['Age'].fillna(mediana_age)

# Visualizzazione risultato finale
print("DataFrame finale:")
display(df)

Dtypes iniziali:
Age    float64
Sex        str
dtype: object
------------------------------
DataFrame finale:

    Age  Sex
0  25.0    M
1  30.0    F
2  37.5  NaN
3  45.0    M
4  37.5    F
5  50.0  NaN

In [ ]:
data = {

    'Age': [25, 30, None, 45, None, 50],

    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']

}


df = pd.DataFrame(data)


display(df.dtypes)


df=df.fillna(df.Age.median()).replace("Unknown", None)

display(df)

Age    float64
Sex        str
dtype: object

    Age  Sex
0  25.0    M
1  30.0    F
2  37.5  NaN
3  45.0    M
4  37.5    F
5  50.0  NaN

fare ulteriore versione che modifica l'originale e non ne crea uno nuovo

provare anche con apply o map

In [28]:
data = {

    'Age': [25, 30, None, 45, None, 50],

    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']

}


df = pd.DataFrame(data)

display(df.dtypes)

def sost(sex):
    if sex=="Unknown":
        return(None)
    return(sex)


df["Age"]=df.Age.apply(lambda p: df.Age.median() if pd.isna(p) else p)
df["Sex"]=df.Sex.apply(sost)

display(df)

Age    float64
Sex        str
dtype: object

    Age  Sex
0  25.0    M
1  30.0    F
2  37.5  NaN
3  45.0    M
4  37.5    F
5  50.0  NaN

In [34]:
data = {

    'Age': [25, 30, None, 45, None, 50],

    'Sex': ['M', 'F', 'Unknown', 'M', 'F', 'Unknown']

}


df = pd.DataFrame(data)

display(df.dtypes)


df.Age=df.Age.apply(lambda p: df.Age.median() if pd.isna(p) else p)
df.Sex=df.Sex.map({"Unknown":None, "M":"M", "F":"F"})

display(df)

Age    float64
Sex        str
dtype: object

    Age  Sex
0  25.0    M
1  30.0    F
2  37.5  NaN
3  45.0    M
4  37.5    F
5  50.0  NaN